# Generated by Django 2.2.4 on 2019-12-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
