# Generated by Django 2.2.4 on 2019-12-26 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=25)),
                ('department', models.CharField(choices=[('Sales', 'Sales'), ('HR ', 'HR'), ('Technology', 'Technology'), ('Accounts', 'Accounts')], default='Sales', max_length=15)),
                ('position', models.CharField(max_length=30)),
                ('salary', models.IntegerField(choices=[(2000, '2000'), (3000, '3000'), (4000, '4000'), (5000, '5000'), (6000, '6000'), (7000, '7000'), (8000, '8000'), (9000, '9000'), (10000, '10000')], default='4000')),
                ('description', models.TextField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
