# Generated by Django 2.2.4 on 2019-12-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_database',
            name='company',
            field=models.CharField(max_length=30),
        ),
    ]
