# Generated by Django 2.2.4 on 2019-12-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0002_auto_20191226_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_database',
            name='salary',
            field=models.IntegerField(choices=[('2000', 2000), ('3000', 3000), ('4000', 4000), ('5000', 5000), ('6000', 6000), ('7000', 7000), ('8000', 8000), ('9000', 9000), ('10000', 10000)], default='4000'),
        ),
    ]
